import { createContext, useContext, useState, useEffect, ReactNode } from "react";

type Language = "en" | "uz" | "ru";

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

const translations: Record<Language, Record<string, string>> = {
  en: {
    // Header
    "nav.home": "Home",
    "nav.industries": "Industries",
    "nav.products": "Products",
    "nav.news": "News",
    "nav.about": "About",
    "nav.investors": "Investors",
    "nav.careers": "Careers",
    "nav.contact": "Contact",
    "header.explore_industries": "Explore 100+ Industries",
    "header.view_all": "View All Industries",
    "header.quick_industries": "Quick Industries",

    // Hero
    "hero.badge": "Innovation Across 100+ Industries",
    "hero.title": "MAKE IT REAL",
    "hero.subtitle": "Building the future of humanity through innovation.",
    "hero.subtitle2": "From AI to Aerospace, Education to Healthcare.",
    "hero.cta_investor": "Become an Investor",
    "hero.cta_explore": "Explore Industries",
    "hero.watch_story": "Watch Our Story",

    // Stats (Hero)
    "stats.industries": "Industries",
    "stats.users": "Users Worldwide",
    "stats.countries": "Countries",
    "stats.assets": "Assets Managed",

    // Stats Section
    "stats_section.badge": "Our Impact",
    "stats_section.title_1": "Numbers That ",
    "stats_section.title_2": "Inspire",
    "stats_section.subtitle": "Every number represents lives changed, innovations delivered, and progress made toward a better future.",
    "stats_section.countries": "Countries",
    "stats_section.countries_desc": "Global presence across continents",
    "stats_section.users": "Users Worldwide",
    "stats_section.users_desc": "People using our products daily",
    "stats_section.industries": "Industries",
    "stats_section.industries_desc": "Sectors we operate in",
    "stats_section.employees": "Employees",
    "stats_section.employees_desc": "Team members worldwide",
    "stats_section.patents": "Patents",
    "stats_section.patents_desc": "Innovations protected globally",
    "stats_section.students": "Students",
    "stats_section.students_desc": "Learning through our platforms",
    "stats_section.patients": "Patients Served",
    "stats_section.patients_desc": "Lives impacted by healthcare",
    "stats_section.launches": "Launches",
    "stats_section.launches_desc": "Space missions completed",

    // Sectors Grid
    "sectors.badge": "Our Ecosystem",
    "sectors.title_1": "100+ Industries, ",
    "sectors.title_2": "One Vision",
    "sectors.subtitle": "From AI to Agriculture, Healthcare to Aerospace — we're building the infrastructure for humanity's future.",
    "sectors.learn_more": "Learn More",
    "sectors.visit_site": "Visit Site",
    "sectors.view_all": "View All {count} Industries",
    "sectors.explore_all": "Explore All Industries",

    // Products Showcase
    "products_showcase.badge": "Latest Innovation",
    "products_showcase.title_1": "Products That Define ",
    "products_showcase.title_2": "Tomorrow",
    "products_showcase.subtitle": "Experience our latest innovations designed to transform your life, work, and the world around you.",
    "products_showcase.explore": "Explore Product",
    "products_showcase.view_all": "View All Products",

    // News Section
    "news_section.badge": "Latest Updates",
    "news_section.title": "News & Insights",
    "news_section.view_all": "View All News",
    "news_section.read_article": "Read Article",

    // CTA Section
    "cta.badge": "Join the Future",
    "cta.title_1": "Ready to Be Part of ",
    "cta.title_2": "Something Extraordinary?",
    "cta.subtitle": "Whether you want to invest, partner, or join our team — we're building the future together. Let's make it real.",
    "cta.investor": "Become an Investor",
    "cta.join_team": "Join Our Team",
    "cta.contact_us": "Contact Us",
    "cta.trusted_by": "Trusted by leading organizations worldwide",

    // Footer
    "footer.newsletter_title": "Stay Updated with ALSAMOS",
    "footer.newsletter_subtitle": "Get the latest news about our innovations, product launches, and investment opportunities.",
    "footer.newsletter_placeholder": "Enter your email",
    "footer.subscribe": "Subscribe",
    "footer.brand_desc": "Building the future of humanity through innovation across 100+ industries worldwide.",
    "footer.company": "Company",
    "footer.industries": "Industries",
    "footer.products": "Products",
    "footer.investors": "Investors",
    "footer.about_us": "About Us",
    "footer.leadership": "Leadership",
    "footer.careers": "Careers",
    "footer.press": "Press",
    "footer.contact": "Contact",
    "footer.it_tech": "IT & Technology",
    "footer.education": "Education",
    "footer.healthcare": "Healthcare",
    "footer.automotive": "Automotive",
    "footer.aerospace": "Aerospace",
    "footer.all_industries": "All Industries",
    "footer.alsamos_cloud": "ALSAMOS Cloud",
    "footer.alsamos_ai": "ALSAMOS AI",
    "footer.alsamos_ev": "ALSAMOS EV",
    "footer.smart_devices": "Smart Devices",
    "footer.all_products": "All Products",
    "footer.investor_relations": "Investor Relations",
    "footer.financial_reports": "Financial Reports",
    "footer.stock_info": "Stock Information",
    "footer.governance": "Governance",
    "footer.become_investor": "Become an Investor",
    "footer.rights": "© {year} ALSAMOS Corporation. All rights reserved.",
    "footer.privacy": "Privacy",
    "footer.terms": "Terms",
    "footer.cookies": "Cookies",
    "footer.sitemap": "Sitemap",

    // About Page
    "about.badge": "About ALSAMOS",
    "about.title_1": "Building the ",
    "about.title_2": "Future",
    "about.title_3": " of Humanity",
    "about.description": "ALSAMOS is a multinational innovation corporation operating across 100+ business sectors, dedicated to transforming industries through cutting-edge technology, sustainable solutions, and visionary leadership.",
    "about.trusted": "Trusted Globally",
    "about.innovation_first": "Innovation First",
    "about.stat_industries": "Industries",
    "about.stat_countries": "Countries",
    "about.stat_employees": "Employees",
    "about.stat_innovations": "Innovations",

    // Founder Section
    "founder.badge": "Meet Our Founder & CEO",
    "founder.title_1": "Visionary Leadership Driving",
    "founder.title_2": "Innovation Across Industries",
    "founder.role": "Businessman • Developer • Economist",
    "founder.description": "A visionary entrepreneur who founded ALSAMOS Corporation with the mission to transform 100+ industries through innovation, technology, and sustainable business practices. Under his leadership, ALSAMOS has grown into a global powerhouse.",
    "founder.tab_overview": "Overview",
    "founder.tab_gallery": "Photo Gallery",
    "founder.tab_biography": "Biography",
    "founder.tab_vision": "Vision & Philosophy",
    "founder.achievements": "Key Achievements",
    "founder.quotes": "Inspiring Quotes",
    "founder.view_full": "View Full Size",
    "founder.bio_title": "The Journey of a Visionary",
    "founder.vision_title": "Our Vision",
    "founder.vision_desc": "To become the world's most innovative and diversified corporation, operating across 100+ industries and impacting billions of lives through technology, education, and sustainable solutions.",
    "founder.philosophy_title": "Our Philosophy",
    "founder.philosophy_desc": "\"Make It Real\" is more than a slogan—it's our way of life. We believe that every ambitious idea deserves a chance to become reality.",

    // Values Section
    "values.badge": "Our Values",
    "values.title": "What Drives Us Forward",
    "values.subtitle": "Our core values are the foundation of everything we do at ALSAMOS.",
    "values.innovation": "Innovation First",
    "values.innovation_desc": "We push boundaries and challenge conventions to create breakthrough solutions.",
    "values.people": "People Centered",
    "values.people_desc": "Every innovation must serve humanity and improve lives meaningfully.",
    "values.integrity": "Integrity Always",
    "values.integrity_desc": "We build trust through transparency, honesty, and ethical practices.",
    "values.sustainability": "Sustainability",
    "values.sustainability_desc": "Building for tomorrow while protecting our planet today.",
    "values.excellence": "Excellence",
    "values.excellence_desc": "We strive for perfection in everything we create and deliver.",
    "values.passion": "Passion",
    "values.passion_desc": "We love what we do and it shows in every product and service.",
    "values.principles_title": "Guiding Principles",
    "values.principles_subtitle": "The principles that guide our daily decisions and actions.",
    "values.think_global": "Think Global, Act Local",
    "values.speed": "Speed Without Compromise",
    "values.customer": "Customer Obsession",
    "values.learning": "Continuous Learning",
    "values.mission_label": "Our Mission",
    "values.mission_text": "\"To transform industries, empower communities, and build a better future for humanity through relentless innovation and unwavering commitment to excellence.\"",
    "values.mission_tagline": "ALSAMOS Corporation — Make It Real",

    // Industries Page
    "industries.title_1": "100+ Industries, ",
    "industries.title_2": "One Vision",
    "industries.subtitle": "From AI to Agriculture, Healthcare to Aerospace — discover how ALSAMOS is building the infrastructure for humanity's future.",
    "industries.search": "Search industries...",
    "industries.showing": "Showing {filtered} of {total} industries",
    "industries.learn_more": "Learn More",
    "industries.visit": "Visit",
    "industries.no_results": "No industries found matching \"{query}\"",

    // Products Page
    "products.badge": "Innovation Portfolio",
    "products.title_1": "Products & ",
    "products.title_2": "Solutions",
    "products.subtitle": "Discover our comprehensive range of innovative products designed to transform industries and empower businesses worldwide.",
    "products.search": "Search products...",
    "products.compare": "Compare Products",
    "products.learn_more": "Learn More",
    "products.no_results": "No products found matching your criteria.",
    "products.clear_filters": "Clear Filters",
    "products.custom_title": "Need a Custom Solution?",
    "products.custom_desc": "Our team of experts can help you find the perfect product or create a tailored solution for your specific needs.",
    "products.contact_sales": "Contact Sales",
    "products.explore_industries": "Explore Industries",

    // News Page
    "news.badge": "News & Insights",
    "news.title_1": "Latest ",
    "news.title_2": "Updates",
    "news.subtitle": "Stay informed with the latest news, insights, and announcements from ALSAMOS and the industries we serve.",
    "news.search": "Search articles...",
    "news.featured": "Featured",
    "news.featured_stories": "Featured Stories",
    "news.all_articles": "All Articles",
    "news.read_more": "Read More",
    "news.no_results": "No articles found matching your criteria.",
    "news.clear_filters": "Clear Filters",
    "news.stay_informed": "Stay Informed",
    "news.newsletter_desc": "Subscribe to our newsletter for the latest updates, insights, and exclusive content delivered directly to your inbox.",
    "news.email_placeholder": "Enter your email",
    "news.subscribe": "Subscribe",

    // Careers Page
    "careers.badge": "Join Our Team",
    "careers.title_1": "Build the ",
    "careers.title_2": "Future",
    "careers.title_3": " With Us",
    "careers.subtitle": "Join a global team of innovators, creators, and problem-solvers who are shaping the future of technology across 100+ industries.",
    "careers.culture_title": "Our Culture",
    "careers.culture_subtitle": "What drives us and defines who we are",
    "careers.benefits_title": "Benefits & Perks",
    "careers.benefits_subtitle": "We take care of our team so they can focus on what matters most",
    "careers.open_positions": "Open Positions",
    "careers.find_opportunity": "Find your next opportunity",
    "careers.search": "Search jobs...",
    "careers.view_job": "View Job",
    "careers.no_results": "No positions found matching your criteria.",
    "careers.clear_filters": "Clear Filters",
    "careers.cta_title": "Don't See the Right Role?",
    "careers.cta_desc": "We're always looking for talented people. Send us your resume and we'll keep you in mind for future opportunities.",
    "careers.send_resume": "Send Your Resume",
    "careers.posted": "Posted",

    // Contact Page
    "contact.badge": "Contact Us",
    "contact.title_1": "Let's ",
    "contact.title_2": "Connect",
    "contact.subtitle": "Have questions or want to discuss a partnership? We'd love to hear from you. Our team is ready to help.",
    "contact.general": "General Inquiry",
    "contact.general_desc": "Questions about ALSAMOS",
    "contact.partnership": "Business Partnership",
    "contact.partnership_desc": "Partnership opportunities",
    "contact.support": "Customer Support",
    "contact.support_desc": "Help with our products",
    "contact.careers_cat": "Careers",
    "contact.careers_desc": "Job opportunities",
    "contact.investor_cat": "Investor Relations",
    "contact.investor_desc": "Investment inquiries",
    "contact.send_message": "Send Us a Message",
    "contact.first_name": "First Name",
    "contact.last_name": "Last Name",
    "contact.email": "Email Address",
    "contact.phone": "Phone Number",
    "contact.subject": "Subject",
    "contact.select_topic": "Select a topic",
    "contact.message": "Message",
    "contact.message_placeholder": "How can we help you?",
    "contact.sending": "Sending...",
    "contact.send": "Send Message",
    "contact.info_title": "Contact Information",
    "contact.email_label": "Email",
    "contact.phone_label": "Phone",
    "contact.headquarters": "Headquarters",
    "contact.business_hours": "Business Hours",
    "contact.hours_value": "Monday - Friday: 9:00 AM - 6:00 PM (UZT)",
    "contact.follow_us": "Follow Us",
    "contact.faq_title": "Frequently Asked Questions",
    "contact.toast_title": "Message Sent!",
    "contact.toast_desc": "Thank you for contacting us. We'll respond within 24-48 hours.",
    "contact.subject_general": "General Inquiry",
    "contact.subject_partnership": "Business Partnership",
    "contact.subject_support": "Customer Support",
    "contact.subject_careers": "Careers",
    "contact.subject_investors": "Investor Relations",
    "contact.subject_media": "Media & Press",
    "contact.subject_other": "Other",

    // Investors Page
    "investors.badge": "Investor Relations",
    "investors.title_1": "Invest in the ",
    "investors.title_2": "Future",
    "investors.subtitle": "Join us in building the future of innovation. ALSAMOS offers unique investment opportunities across 100+ industries with proven growth and strong fundamentals.",
    "investors.become_investor": "Become an Investor",
    "investors.download_deck": "Download Deck",
    "investors.performance": "Performance",
    "investors.key_metrics": "Key Metrics",
    "investors.at_a_glance": "Our performance at a glance",
    "investors.growth_title": "Growth Trajectory",
    "investors.growth_subtitle": "Consistent growth across all metrics",
    "investors.revenue_growth": "Revenue Growth ($M)",
    "investors.revenue_by_sector": "Revenue by Sector",
    "investors.opportunities_title": "Investment Opportunities",
    "investors.opportunities_subtitle": "Current opportunities to invest in ALSAMOS",
    "investors.min_investment": "Min. Investment",
    "investors.status": "Status",
    "investors.deadline": "Deadline",
    "investors.learn_more": "Learn More",
    "investors.documents_title": "Investor Documents",
    "investors.documents_subtitle": "Download our latest reports and presentations",
    "investors.download": "Download",
    "investors.contact_title": "Get in Touch",
    "investors.contact_subtitle": "Interested in investing? Fill out the form and our team will contact you.",
    "investors.toast_title": "Thank You for Your Interest!",
    "investors.toast_desc": "Our investor relations team will contact you within 2 business days.",

    // Contact - FAQ
    "contact.faq_subtitle": "Quick answers to common questions",
    "contact.map_title": "Our Global Presence",
    "contact.map_subtitle": "Offices in major cities worldwide",

    // Investors - Form
    "investors.request_info": "Request Information",
    "investors.first_name": "First Name",
    "investors.last_name": "Last Name",
    "investors.email_label": "Email Address",
    "investors.company": "Company/Organization",
    "investors.investment_range": "Investment Range",
    "investors.investment_placeholder": "e.g., $500K - $1M",
    "investors.message": "Message",
    "investors.message_placeholder": "Tell us about your investment interests...",
    "investors.submitting": "Submitting...",
    "investors.submit": "Submit Request",
    "investors.contact_desc": "Interested in investing with ALSAMOS? Our investor relations team is ready to answer your questions and discuss opportunities.",

    // Careers - extra
    "careers.cta_button": "Get in Touch",

    // 404
    "notfound.title": "404",
    "notfound.message": "Oops! Page not found",
    "notfound.back": "Return to Home",

    // Common
    "common.learn_more": "Learn More",
    "common.visit_site": "Visit Site",
    "common.read_more": "Read More",
    "common.view_all": "View All",
    "common.search": "Search...",
  },
  uz: {
    // Header
    "nav.home": "Bosh sahifa",
    "nav.industries": "Sohalar",
    "nav.products": "Mahsulotlar",
    "nav.news": "Yangiliklar",
    "nav.about": "Biz haqimizda",
    "nav.investors": "Investorlar",
    "nav.careers": "Karyera",
    "nav.contact": "Aloqa",
    "header.explore_industries": "100+ sohani o'rganing",
    "header.view_all": "Barcha sohalar",
    "header.quick_industries": "Tezkor sohalar",

    // Hero
    "hero.badge": "100+ sohada innovatsiya",
    "hero.title": "HAQIQATGA AYLANTIR",
    "hero.subtitle": "Innovatsiya orqali insoniyat kelajagini quramiz.",
    "hero.subtitle2": "Sun'iy intellektdan kosmik texnologiyagacha, ta'limdan sog'liqni saqlashgacha.",
    "hero.cta_investor": "Investor bo'ling",
    "hero.cta_explore": "Sohalarni o'rganing",
    "hero.watch_story": "Bizning hikoyamiz",

    // Stats (Hero)
    "stats.industries": "Sohalar",
    "stats.users": "Foydalanuvchilar",
    "stats.countries": "Mamlakatlar",
    "stats.assets": "Boshqariladigan aktivlar",

    // Stats Section
    "stats_section.badge": "Bizning ta'sirimiz",
    "stats_section.title_1": "Ilhomlantiruvchi ",
    "stats_section.title_2": "raqamlar",
    "stats_section.subtitle": "Har bir raqam o'zgartirilgan hayotlarni, yaratilgan innovatsiyalarni va yaxshiroq kelajak sari qilingan yutuqlarni anglatadi.",
    "stats_section.countries": "Mamlakatlar",
    "stats_section.countries_desc": "Qit'alardagi global mavjudlik",
    "stats_section.users": "Foydalanuvchilar",
    "stats_section.users_desc": "Mahsulotlarimizdan kundalik foydalanuvchilar",
    "stats_section.industries": "Sohalar",
    "stats_section.industries_desc": "Biz faoliyat yuritadigan tarmoqlar",
    "stats_section.employees": "Xodimlar",
    "stats_section.employees_desc": "Butun dunyo bo'ylab jamoa a'zolari",
    "stats_section.patents": "Patentlar",
    "stats_section.patents_desc": "Global miqyosda himoyalangan innovatsiyalar",
    "stats_section.students": "Talabalar",
    "stats_section.students_desc": "Platformalarimiz orqali o'qiyotganlar",
    "stats_section.patients": "Bemorlar",
    "stats_section.patients_desc": "Sog'liqni saqlash ta'sir etgan hayotlar",
    "stats_section.launches": "Uchirish",
    "stats_section.launches_desc": "Kosmik missiyalar bajarildi",

    // Sectors Grid
    "sectors.badge": "Bizning ekotizim",
    "sectors.title_1": "100+ soha, ",
    "sectors.title_2": "bitta maqsad",
    "sectors.subtitle": "Sun'iy intellektdan qishloq xo'jaligigacha, sog'liqni saqlashdan kosmik texnologiyagacha — insoniyat kelajagi uchun infratuzilma quramiz.",
    "sectors.learn_more": "Batafsil",
    "sectors.visit_site": "Saytga o'tish",
    "sectors.view_all": "Barcha {count} sohani ko'rish",
    "sectors.explore_all": "Barcha sohalarni o'rganing",

    // Products Showcase
    "products_showcase.badge": "So'nggi innovatsiya",
    "products_showcase.title_1": "Ertangi kunni belgilaydigan ",
    "products_showcase.title_2": "mahsulotlar",
    "products_showcase.subtitle": "Hayotingizni, ishingizni va atrofingizdagi dunyoni o'zgartirishga mo'ljallangan eng so'nggi innovatsiyalarimizni kashf eting.",
    "products_showcase.explore": "Mahsulotni o'rganing",
    "products_showcase.view_all": "Barcha mahsulotlar",

    // News Section
    "news_section.badge": "So'nggi yangiliklar",
    "news_section.title": "Yangiliklar va tushunchalar",
    "news_section.view_all": "Barcha yangiliklar",
    "news_section.read_article": "Maqolani o'qish",

    // CTA Section
    "cta.badge": "Kelajakka qo'shiling",
    "cta.title_1": "Favqulodda narsaning ",
    "cta.title_2": "bir qismi bo'lishga tayyormisiz?",
    "cta.subtitle": "Investitsiya qilmoqchimisiz, hamkorlik qilmoqchimisiz yoki jamoamizga qo'shilmoqchimisiz — biz birgalikda kelajakni quramiz.",
    "cta.investor": "Investor bo'ling",
    "cta.join_team": "Jamoamizga qo'shiling",
    "cta.contact_us": "Biz bilan bog'laning",
    "cta.trusted_by": "Dunyo bo'ylab yetakchi tashkilotlar tomonidan ishoniladi",

    // Footer
    "footer.newsletter_title": "ALSAMOS yangiliklaridan xabardor bo'ling",
    "footer.newsletter_subtitle": "Innovatsiyalarimiz, mahsulot chiqarishlari va investitsiya imkoniyatlari haqida so'nggi yangiliklar.",
    "footer.newsletter_placeholder": "Emailingizni kiriting",
    "footer.subscribe": "Obuna bo'lish",
    "footer.brand_desc": "Innovatsiya orqali 100+ sohada insoniyat kelajagini quramiz.",
    "footer.company": "Kompaniya",
    "footer.industries": "Sohalar",
    "footer.products": "Mahsulotlar",
    "footer.investors": "Investorlar",
    "footer.about_us": "Biz haqimizda",
    "footer.leadership": "Rahbariyat",
    "footer.careers": "Karyera",
    "footer.press": "Matbuot",
    "footer.contact": "Aloqa",
    "footer.it_tech": "IT va Texnologiya",
    "footer.education": "Ta'lim",
    "footer.healthcare": "Sog'liqni saqlash",
    "footer.automotive": "Avtomobil sanoati",
    "footer.aerospace": "Kosmik texnologiya",
    "footer.all_industries": "Barcha sohalar",
    "footer.alsamos_cloud": "ALSAMOS Cloud",
    "footer.alsamos_ai": "ALSAMOS AI",
    "footer.alsamos_ev": "ALSAMOS EV",
    "footer.smart_devices": "Aqlli qurilmalar",
    "footer.all_products": "Barcha mahsulotlar",
    "footer.investor_relations": "Investor munosabatlari",
    "footer.financial_reports": "Moliyaviy hisobotlar",
    "footer.stock_info": "Aksiya ma'lumotlari",
    "footer.governance": "Boshqaruv",
    "footer.become_investor": "Investor bo'ling",
    "footer.rights": "© {year} ALSAMOS Corporation. Barcha huquqlar himoyalangan.",
    "footer.privacy": "Maxfiylik",
    "footer.terms": "Shartlar",
    "footer.cookies": "Cookie",
    "footer.sitemap": "Sayt xaritasi",

    // About Page
    "about.badge": "ALSAMOS haqida",
    "about.title_1": "Insoniyat ",
    "about.title_2": "kelajagini",
    "about.title_3": " quramiz",
    "about.description": "ALSAMOS — 100+ biznes sohada faoliyat yurituvchi ko'p millatli innovatsion korporatsiya bo'lib, ilg'or texnologiya, barqaror yechimlar va uzoqni ko'ra biluvchi rahbarlik orqali sohalarni o'zgartishga bag'ishlangan.",
    "about.trusted": "Global miqyosda ishonchli",
    "about.innovation_first": "Avvalo innovatsiya",
    "about.stat_industries": "Sohalar",
    "about.stat_countries": "Mamlakatlar",
    "about.stat_employees": "Xodimlar",
    "about.stat_innovations": "Innovatsiyalar",

    // Founder Section
    "founder.badge": "Asoschimiz va bosh direktormiz bilan tanishing",
    "founder.title_1": "Innovatsiyani boshqaruvchi",
    "founder.title_2": "vizioner rahbariyat",
    "founder.role": "Tadbirkor • Dasturchi • Iqtisodchi",
    "founder.description": "100+ sohani innovatsiya, texnologiya va barqaror biznes amaliyotlari orqali o'zgartirish missiyasi bilan ALSAMOS Korporatsiyasini asos solgan vizioner tadbirkor.",
    "founder.tab_overview": "Umumiy ma'lumot",
    "founder.tab_gallery": "Fotogalereya",
    "founder.tab_biography": "Tarjimai hol",
    "founder.tab_vision": "Vizyon va falsafa",
    "founder.achievements": "Asosiy yutuqlar",
    "founder.quotes": "Ilhomlantiruvchi iqtiboslar",
    "founder.view_full": "To'liq ko'rish",
    "founder.bio_title": "Vizioner sayohati",
    "founder.vision_title": "Bizning vizyonimiz",
    "founder.vision_desc": "Dunyoning eng innovatsion va diversifikatsiyalangan korporatsiyasiga aylanish, 100+ sohada faoliyat yuritish va milliardlab hayotlarga ta'sir qilish.",
    "founder.philosophy_title": "Bizning falsafamiz",
    "founder.philosophy_desc": "\"Haqiqatga aylantir\" shunchaki shior emas — bu bizning hayot tarzimiz.",

    // Values Section
    "values.badge": "Qadriyatlarimiz",
    "values.title": "Bizni oldinga yetaklaydigan narsa",
    "values.subtitle": "ALSAMOS'da qiladigan har bir ishimiz asosida bizning asosiy qadriyatlarimiz yotadi.",
    "values.innovation": "Avvalo innovatsiya",
    "values.innovation_desc": "Biz chegaralarni kengaytiramiz va konvensiyalarga qarshi chiqamiz.",
    "values.people": "Inson markazda",
    "values.people_desc": "Har bir innovatsiya insoniyatga xizmat qilishi kerak.",
    "values.integrity": "Doimo halollik",
    "values.integrity_desc": "Biz shaffoflik, halollik va axloqiy amaliyotlar orqali ishonch quramiz.",
    "values.sustainability": "Barqarorlik",
    "values.sustainability_desc": "Sayyoramizni himoya qilgan holda ertangi kun uchun quramiz.",
    "values.excellence": "Mukammallik",
    "values.excellence_desc": "Biz yaratgan va taqdim etgan hamma narsada mukammallikka intilamiz.",
    "values.passion": "Ishtiyoq",
    "values.passion_desc": "Biz o'z ishimizni sevamiz va bu har bir mahsulotda ko'rinadi.",
    "values.principles_title": "Yo'l ko'rsatuvchi tamoyillar",
    "values.principles_subtitle": "Kundalik qarorlar va harakatlarimizga yo'nalish beradigan tamoyillar.",
    "values.think_global": "Global fikrla, mahalliy harakat qil",
    "values.speed": "Murosasiz tezlik",
    "values.customer": "Mijozga yo'naltirilganlik",
    "values.learning": "Doimiy o'qish",
    "values.mission_label": "Bizning missiyamiz",
    "values.mission_text": "\"Sohalarni o'zgartirish, jamiyatlarni kuchaytirish va tinimsiz innovatsiya va mukammallikka bo'lgan sodiqlik orqali insoniyat uchun yaxshiroq kelajak qurish.\"",
    "values.mission_tagline": "ALSAMOS Corporation — Haqiqatga aylantir",

    // Industries Page
    "industries.title_1": "100+ soha, ",
    "industries.title_2": "bitta maqsad",
    "industries.subtitle": "Sun'iy intellektdan qishloq xo'jaligigacha, sog'liqni saqlashdan kosmik texnologiyagacha — ALSAMOS insoniyat kelajagi uchun infratuzilma qanday qurayotganini bilib oling.",
    "industries.search": "Sohalarni qidirish...",
    "industries.showing": "{total} dan {filtered} ta soha ko'rsatilmoqda",
    "industries.learn_more": "Batafsil",
    "industries.visit": "Tashrif buyurish",
    "industries.no_results": "\"{query}\" bo'yicha sohalar topilmadi",

    // Products Page
    "products.badge": "Innovatsiya portfeli",
    "products.title_1": "Mahsulotlar va ",
    "products.title_2": "yechimlar",
    "products.subtitle": "Sohalarni o'zgartirishga va butun dunyo bo'ylab bizneslarni kuchantirishga mo'ljallangan innovatsion mahsulotlarimiz assortimentini kashf eting.",
    "products.search": "Mahsulotlarni qidirish...",
    "products.compare": "Mahsulotlarni solishtirish",
    "products.learn_more": "Batafsil",
    "products.no_results": "Mezonlaringizga mos mahsulotlar topilmadi.",
    "products.clear_filters": "Filtrlarni tozalash",
    "products.custom_title": "Maxsus yechim kerakmi?",
    "products.custom_desc": "Mutaxassislar jamoamiz sizga mukammal mahsulot topishga yoki ehtiyojlaringizga moslashtirilgan yechim yaratishga yordam beradi.",
    "products.contact_sales": "Sotuvga murojaat",
    "products.explore_industries": "Sohalarni o'rganing",

    // News Page
    "news.badge": "Yangiliklar va tushunchalar",
    "news.title_1": "So'nggi ",
    "news.title_2": "yangiliklar",
    "news.subtitle": "ALSAMOS va biz xizmat qiladigan sohalardan so'nggi yangiliklar, tushunchalar va e'lonlar bilan xabardor bo'ling.",
    "news.search": "Maqolalarni qidirish...",
    "news.featured": "Tanlangan",
    "news.featured_stories": "Tanlangan hikoyalar",
    "news.all_articles": "Barcha maqolalar",
    "news.read_more": "Davomini o'qish",
    "news.no_results": "Mezonlaringizga mos maqolalar topilmadi.",
    "news.clear_filters": "Filtrlarni tozalash",
    "news.stay_informed": "Xabardor bo'ling",
    "news.newsletter_desc": "So'nggi yangiliklar, tushunchalar va eksklyuziv kontentni to'g'ridan-to'g'ri pochta qutingizga olish uchun obuna bo'ling.",
    "news.email_placeholder": "Emailingizni kiriting",
    "news.subscribe": "Obuna bo'lish",

    // Careers Page
    "careers.badge": "Jamoamizga qo'shiling",
    "careers.title_1": "Biz bilan ",
    "careers.title_2": "kelajakni",
    "careers.title_3": " quring",
    "careers.subtitle": "100+ sohada texnologiya kelajagini shakllantirayotgan innovatorlar, ijodkorlar va muammolarni hal qiluvchilardan iborat global jamoaga qo'shiling.",
    "careers.culture_title": "Bizning madaniyatimiz",
    "careers.culture_subtitle": "Bizni harakatga keltiruvchi va belgilovchi narsa",
    "careers.benefits_title": "Imtiyozlar va afzalliklar",
    "careers.benefits_subtitle": "Biz jamoamiz haqida g'amxo'rlik qilamiz",
    "careers.open_positions": "Ochiq lavozimlar",
    "careers.find_opportunity": "Keyingi imkoniyatingizni toping",
    "careers.search": "Ishlarni qidirish...",
    "careers.view_job": "Ishni ko'rish",
    "careers.no_results": "Mezonlaringizga mos lavozimlar topilmadi.",
    "careers.clear_filters": "Filtrlarni tozalash",
    "careers.cta_title": "Mos rolni ko'rmayapsizmi?",
    "careers.cta_desc": "Biz doimo iste'dodli odamlarni qidiramiz. Rezyumeyingizni yuboring va kelajakdagi imkoniyatlar uchun saqlab qo'yamiz.",
    "careers.send_resume": "Rezyumeyingizni yuboring",
    "careers.posted": "E'lon qilingan",

    // Contact Page
    "contact.badge": "Biz bilan bog'laning",
    "contact.title_1": "Keling ",
    "contact.title_2": "bog'lanamiz",
    "contact.subtitle": "Savollaringiz bormi yoki hamkorlikni muhokama qilmoqchimisiz? Sizdan eshitishdan xursand bo'lamiz.",
    "contact.general": "Umumiy so'rov",
    "contact.general_desc": "ALSAMOS haqida savollar",
    "contact.partnership": "Biznes hamkorlik",
    "contact.partnership_desc": "Hamkorlik imkoniyatlari",
    "contact.support": "Mijozlarni qo'llab-quvvatlash",
    "contact.support_desc": "Mahsulotlarimiz bo'yicha yordam",
    "contact.careers_cat": "Karyera",
    "contact.careers_desc": "Ish imkoniyatlari",
    "contact.investor_cat": "Investor munosabatlari",
    "contact.investor_desc": "Investitsiya so'rovlari",
    "contact.send_message": "Xabar yuboring",
    "contact.first_name": "Ism",
    "contact.last_name": "Familiya",
    "contact.email": "Email manzil",
    "contact.phone": "Telefon raqam",
    "contact.subject": "Mavzu",
    "contact.select_topic": "Mavzuni tanlang",
    "contact.message": "Xabar",
    "contact.message_placeholder": "Sizga qanday yordam bera olamiz?",
    "contact.sending": "Yuborilmoqda...",
    "contact.send": "Xabar yuborish",
    "contact.info_title": "Aloqa ma'lumotlari",
    "contact.email_label": "Email",
    "contact.phone_label": "Telefon",
    "contact.headquarters": "Bosh ofis",
    "contact.business_hours": "Ish vaqti",
    "contact.hours_value": "Dushanba - Juma: 9:00 - 18:00 (O'zbekiston vaqti)",
    "contact.follow_us": "Bizni kuzating",
    "contact.faq_title": "Ko'p beriladigan savollar",
    "contact.toast_title": "Xabar yuborildi!",
    "contact.toast_desc": "Biz bilan bog'langaningiz uchun rahmat. 24-48 soat ichida javob beramiz.",
    "contact.subject_general": "Umumiy so'rov",
    "contact.subject_partnership": "Biznes hamkorlik",
    "contact.subject_support": "Mijozlarni qo'llab-quvvatlash",
    "contact.subject_careers": "Karyera",
    "contact.subject_investors": "Investor munosabatlari",
    "contact.subject_media": "Media va matbuot",
    "contact.subject_other": "Boshqa",

    // Investors Page
    "investors.badge": "Investor munosabatlari",
    "investors.title_1": "Kelajakka ",
    "investors.title_2": "investitsiya qiling",
    "investors.subtitle": "Innovatsiya kelajagini qurish uchun bizga qo'shiling. ALSAMOS 100+ sohada o'sishi isbotlangan noyob investitsiya imkoniyatlarini taklif etadi.",
    "investors.become_investor": "Investor bo'ling",
    "investors.download_deck": "Taqdimotni yuklash",
    "investors.performance": "Samaradorlik",
    "investors.key_metrics": "Asosiy ko'rsatkichlar",
    "investors.at_a_glance": "Bir qarashda samaradorligimiz",
    "investors.growth_title": "O'sish trajektoriyasi",
    "investors.growth_subtitle": "Barcha ko'rsatkichlarda barqaror o'sish",
    "investors.revenue_growth": "Daromad o'sishi ($M)",
    "investors.revenue_by_sector": "Soha bo'yicha daromad",
    "investors.opportunities_title": "Investitsiya imkoniyatlari",
    "investors.opportunities_subtitle": "ALSAMOS'ga investitsiya qilish uchun joriy imkoniyatlar",
    "investors.min_investment": "Min. investitsiya",
    "investors.status": "Holat",
    "investors.deadline": "Muddat",
    "investors.learn_more": "Batafsil",
    "investors.documents_title": "Investor hujjatlari",
    "investors.documents_subtitle": "Eng so'nggi hisobotlar va taqdimotlarimizni yuklab oling",
    "investors.download": "Yuklash",
    "investors.contact_title": "Biz bilan bog'laning",
    "investors.contact_subtitle": "Investitsiya qilishga qiziqyapsizmi? Formani to'ldiring, jamoamiz siz bilan bog'lanadi.",
    "investors.toast_title": "Qiziqishingiz uchun rahmat!",
    "investors.toast_desc": "Investor munosabatlari jamoamiz 2 ish kuni ichida siz bilan bog'lanadi.",

    // Contact - FAQ
    "contact.faq_subtitle": "Ko'p beriladigan savollarga tezkor javoblar",
    "contact.map_title": "Bizning global mavjudligimiz",
    "contact.map_subtitle": "Dunyo bo'ylab yirik shaharlardagi ofislar",

    // Investors - Form
    "investors.request_info": "Ma'lumot so'rash",
    "investors.first_name": "Ism",
    "investors.last_name": "Familiya",
    "investors.email_label": "Email manzil",
    "investors.company": "Kompaniya/Tashkilot",
    "investors.investment_range": "Investitsiya miqdori",
    "investors.investment_placeholder": "masalan, $500K - $1M",
    "investors.message": "Xabar",
    "investors.message_placeholder": "Investitsiya qiziqishlaringiz haqida aytib bering...",
    "investors.submitting": "Yuborilmoqda...",
    "investors.submit": "So'rov yuborish",
    "investors.contact_desc": "ALSAMOS bilan investitsiya qilishga qiziqyapsizmi? Investor munosabatlari jamoamiz savollaringizga javob berishga va imkoniyatlarni muhokama qilishga tayyor.",

    // Careers - extra
    "careers.cta_button": "Bog'lanish",

    // 404
    "notfound.title": "404",
    "notfound.message": "Kechirasiz! Sahifa topilmadi",
    "notfound.back": "Bosh sahifaga qaytish",

    // Common
    "common.learn_more": "Batafsil",
    "common.visit_site": "Saytga o'tish",
    "common.read_more": "Davomini o'qish",
    "common.view_all": "Barchasini ko'rish",
    "common.search": "Qidirish...",
  },
  ru: {
    // Header
    "nav.home": "Главная",
    "nav.industries": "Индустрии",
    "nav.products": "Продукты",
    "nav.news": "Новости",
    "nav.about": "О нас",
    "nav.investors": "Инвесторы",
    "nav.careers": "Карьера",
    "nav.contact": "Контакты",
    "header.explore_industries": "Изучите 100+ индустрий",
    "header.view_all": "Все индустрии",
    "header.quick_industries": "Быстрые индустрии",

    // Hero
    "hero.badge": "Инновации в 100+ индустриях",
    "hero.title": "ВОПЛОЩАЕМ В РЕАЛЬНОСТЬ",
    "hero.subtitle": "Строим будущее человечества через инновации.",
    "hero.subtitle2": "От ИИ до аэрокосмических технологий, от образования до здравоохранения.",
    "hero.cta_investor": "Стать инвестором",
    "hero.cta_explore": "Изучить индустрии",
    "hero.watch_story": "Наша история",

    // Stats (Hero)
    "stats.industries": "Индустрий",
    "stats.users": "Пользователей",
    "stats.countries": "Стран",
    "stats.assets": "Управляемые активы",

    // Stats Section
    "stats_section.badge": "Наше влияние",
    "stats_section.title_1": "Вдохновляющие ",
    "stats_section.title_2": "цифры",
    "stats_section.subtitle": "Каждая цифра представляет изменённые жизни, созданные инновации и прогресс к лучшему будущему.",
    "stats_section.countries": "Стран",
    "stats_section.countries_desc": "Глобальное присутствие на континентах",
    "stats_section.users": "Пользователей",
    "stats_section.users_desc": "Ежедневно используют наши продукты",
    "stats_section.industries": "Индустрий",
    "stats_section.industries_desc": "Секторов, в которых мы работаем",
    "stats_section.employees": "Сотрудников",
    "stats_section.employees_desc": "Членов команды по всему миру",
    "stats_section.patents": "Патентов",
    "stats_section.patents_desc": "Инноваций защищено глобально",
    "stats_section.students": "Студентов",
    "stats_section.students_desc": "Обучаются через наши платформы",
    "stats_section.patients": "Пациентов",
    "stats_section.patients_desc": "Жизней, затронутых здравоохранением",
    "stats_section.launches": "Запусков",
    "stats_section.launches_desc": "Космических миссий выполнено",

    // Sectors Grid
    "sectors.badge": "Наша экосистема",
    "sectors.title_1": "100+ индустрий, ",
    "sectors.title_2": "одна цель",
    "sectors.subtitle": "От ИИ до сельского хозяйства, от здравоохранения до аэрокосмических технологий — мы строим инфраструктуру для будущего человечества.",
    "sectors.learn_more": "Подробнее",
    "sectors.visit_site": "Перейти на сайт",
    "sectors.view_all": "Все {count} индустрий",
    "sectors.explore_all": "Изучить все индустрии",

    // Products Showcase
    "products_showcase.badge": "Последние инновации",
    "products_showcase.title_1": "Продукты, определяющие ",
    "products_showcase.title_2": "завтра",
    "products_showcase.subtitle": "Познакомьтесь с нашими новейшими инновациями, созданными для преобразования вашей жизни и работы.",
    "products_showcase.explore": "Изучить продукт",
    "products_showcase.view_all": "Все продукты",

    // News Section
    "news_section.badge": "Последние обновления",
    "news_section.title": "Новости и аналитика",
    "news_section.view_all": "Все новости",
    "news_section.read_article": "Читать статью",

    // CTA Section
    "cta.badge": "Присоединяйтесь к будущему",
    "cta.title_1": "Готовы стать частью ",
    "cta.title_2": "чего-то необычного?",
    "cta.subtitle": "Хотите инвестировать, сотрудничать или присоединиться к нашей команде — мы строим будущее вместе.",
    "cta.investor": "Стать инвестором",
    "cta.join_team": "Присоединиться к команде",
    "cta.contact_us": "Связаться с нами",
    "cta.trusted_by": "Нам доверяют ведущие организации мира",

    // Footer
    "footer.newsletter_title": "Будьте в курсе новостей ALSAMOS",
    "footer.newsletter_subtitle": "Получайте последние новости об инновациях, запусках продуктов и инвестиционных возможностях.",
    "footer.newsletter_placeholder": "Введите ваш email",
    "footer.subscribe": "Подписаться",
    "footer.brand_desc": "Строим будущее человечества через инновации в 100+ индустриях по всему миру.",
    "footer.company": "Компания",
    "footer.industries": "Индустрии",
    "footer.products": "Продукты",
    "footer.investors": "Инвесторы",
    "footer.about_us": "О нас",
    "footer.leadership": "Руководство",
    "footer.careers": "Карьера",
    "footer.press": "Пресса",
    "footer.contact": "Контакты",
    "footer.it_tech": "IT и технологии",
    "footer.education": "Образование",
    "footer.healthcare": "Здравоохранение",
    "footer.automotive": "Автомобильная отрасль",
    "footer.aerospace": "Аэрокосмическая отрасль",
    "footer.all_industries": "Все индустрии",
    "footer.alsamos_cloud": "ALSAMOS Cloud",
    "footer.alsamos_ai": "ALSAMOS AI",
    "footer.alsamos_ev": "ALSAMOS EV",
    "footer.smart_devices": "Умные устройства",
    "footer.all_products": "Все продукты",
    "footer.investor_relations": "Отношения с инвесторами",
    "footer.financial_reports": "Финансовые отчёты",
    "footer.stock_info": "Информация об акциях",
    "footer.governance": "Управление",
    "footer.become_investor": "Стать инвестором",
    "footer.rights": "© {year} ALSAMOS Corporation. Все права защищены.",
    "footer.privacy": "Конфиденциальность",
    "footer.terms": "Условия",
    "footer.cookies": "Cookie",
    "footer.sitemap": "Карта сайта",

    // About Page
    "about.badge": "Об ALSAMOS",
    "about.title_1": "Строим ",
    "about.title_2": "будущее",
    "about.title_3": " человечества",
    "about.description": "ALSAMOS — многонациональная инновационная корпорация, работающая в 100+ бизнес-секторах, посвящённая преобразованию отраслей через передовые технологии, устойчивые решения и дальновидное руководство.",
    "about.trusted": "Доверие во всём мире",
    "about.innovation_first": "Инновации прежде всего",
    "about.stat_industries": "Индустрий",
    "about.stat_countries": "Стран",
    "about.stat_employees": "Сотрудников",
    "about.stat_innovations": "Инноваций",

    // Founder Section
    "founder.badge": "Познакомьтесь с основателем и генеральным директором",
    "founder.title_1": "Визионерское лидерство, движущее",
    "founder.title_2": "инновации в отраслях",
    "founder.role": "Бизнесмен • Разработчик • Экономист",
    "founder.description": "Визионер-предприниматель, основавший корпорацию ALSAMOS с миссией трансформации 100+ отраслей через инновации, технологии и устойчивые бизнес-практики.",
    "founder.tab_overview": "Обзор",
    "founder.tab_gallery": "Фотогалерея",
    "founder.tab_biography": "Биография",
    "founder.tab_vision": "Видение и философия",
    "founder.achievements": "Ключевые достижения",
    "founder.quotes": "Вдохновляющие цитаты",
    "founder.view_full": "Полный размер",
    "founder.bio_title": "Путь визионера",
    "founder.vision_title": "Наше видение",
    "founder.vision_desc": "Стать самой инновационной и диверсифицированной корпорацией в мире, работающей в 100+ отраслях и влияющей на миллиарды жизней.",
    "founder.philosophy_title": "Наша философия",
    "founder.philosophy_desc": "\"Воплощаем в реальность\" — это больше чем слоган, это наш образ жизни.",

    // Values Section
    "values.badge": "Наши ценности",
    "values.title": "Что движет нами вперёд",
    "values.subtitle": "Наши основные ценности — фундамент всего, что мы делаем в ALSAMOS.",
    "values.innovation": "Инновации прежде всего",
    "values.innovation_desc": "Мы раздвигаем границы и бросаем вызов условностям.",
    "values.people": "Люди в центре",
    "values.people_desc": "Каждая инновация должна служить человечеству.",
    "values.integrity": "Всегда честность",
    "values.integrity_desc": "Мы строим доверие через прозрачность и этичные практики.",
    "values.sustainability": "Устойчивость",
    "values.sustainability_desc": "Строим для завтра, защищая планету сегодня.",
    "values.excellence": "Превосходство",
    "values.excellence_desc": "Мы стремимся к совершенству во всём.",
    "values.passion": "Страсть",
    "values.passion_desc": "Мы любим то, что делаем, и это видно.",
    "values.principles_title": "Руководящие принципы",
    "values.principles_subtitle": "Принципы, которые направляют наши ежедневные решения.",
    "values.think_global": "Думай глобально, действуй локально",
    "values.speed": "Скорость без компромиссов",
    "values.customer": "Одержимость клиентом",
    "values.learning": "Непрерывное обучение",
    "values.mission_label": "Наша миссия",
    "values.mission_text": "\"Трансформировать отрасли, укреплять сообщества и строить лучшее будущее для человечества через неустанные инновации и непоколебимую приверженность совершенству.\"",
    "values.mission_tagline": "ALSAMOS Corporation — Воплощаем в реальность",

    // Industries Page
    "industries.title_1": "100+ индустрий, ",
    "industries.title_2": "одна цель",
    "industries.subtitle": "От ИИ до сельского хозяйства, от здравоохранения до аэрокосмических технологий — узнайте, как ALSAMOS строит инфраструктуру для будущего.",
    "industries.search": "Поиск индустрий...",
    "industries.showing": "Показано {filtered} из {total} индустрий",
    "industries.learn_more": "Подробнее",
    "industries.visit": "Перейти",
    "industries.no_results": "Индустрии по запросу \"{query}\" не найдены",

    // Products Page
    "products.badge": "Портфолио инноваций",
    "products.title_1": "Продукты и ",
    "products.title_2": "решения",
    "products.subtitle": "Откройте для себя наш комплексный ассортимент инновационных продуктов, созданных для трансформации отраслей.",
    "products.search": "Поиск продуктов...",
    "products.compare": "Сравнить продукты",
    "products.learn_more": "Подробнее",
    "products.no_results": "Продукты по вашим критериям не найдены.",
    "products.clear_filters": "Очистить фильтры",
    "products.custom_title": "Нужно индивидуальное решение?",
    "products.custom_desc": "Наша команда экспертов поможет найти идеальный продукт или создать решение под ваши нужды.",
    "products.contact_sales": "Связаться с отделом продаж",
    "products.explore_industries": "Изучить индустрии",

    // News Page
    "news.badge": "Новости и аналитика",
    "news.title_1": "Последние ",
    "news.title_2": "обновления",
    "news.subtitle": "Будьте в курсе последних новостей, аналитики и объявлений ALSAMOS.",
    "news.search": "Поиск статей...",
    "news.featured": "Избранное",
    "news.featured_stories": "Избранные истории",
    "news.all_articles": "Все статьи",
    "news.read_more": "Читать далее",
    "news.no_results": "Статьи по вашим критериям не найдены.",
    "news.clear_filters": "Очистить фильтры",
    "news.stay_informed": "Будьте в курсе",
    "news.newsletter_desc": "Подпишитесь на рассылку, чтобы получать последние обновления и эксклюзивный контент прямо на почту.",
    "news.email_placeholder": "Введите ваш email",
    "news.subscribe": "Подписаться",

    // Careers Page
    "careers.badge": "Присоединяйтесь к команде",
    "careers.title_1": "Стройте ",
    "careers.title_2": "будущее",
    "careers.title_3": " вместе с нами",
    "careers.subtitle": "Присоединяйтесь к глобальной команде инноваторов, создателей и решателей проблем, формирующих будущее технологий в 100+ отраслях.",
    "careers.culture_title": "Наша культура",
    "careers.culture_subtitle": "Что движет нами и определяет нас",
    "careers.benefits_title": "Преимущества и бонусы",
    "careers.benefits_subtitle": "Мы заботимся о нашей команде",
    "careers.open_positions": "Открытые вакансии",
    "careers.find_opportunity": "Найдите вашу следующую возможность",
    "careers.search": "Поиск вакансий...",
    "careers.view_job": "Посмотреть",
    "careers.no_results": "Вакансии по вашим критериям не найдены.",
    "careers.clear_filters": "Очистить фильтры",
    "careers.cta_title": "Не нашли подходящую роль?",
    "careers.cta_desc": "Мы всегда ищем талантливых людей. Отправьте резюме, и мы свяжемся с вами при появлении подходящих вакансий.",
    "careers.send_resume": "Отправить резюме",
    "careers.posted": "Опубликовано",

    // Contact Page
    "contact.badge": "Свяжитесь с нами",
    "contact.title_1": "Давайте ",
    "contact.title_2": "свяжемся",
    "contact.subtitle": "Есть вопросы или хотите обсудить сотрудничество? Мы будем рады услышать вас.",
    "contact.general": "Общий запрос",
    "contact.general_desc": "Вопросы об ALSAMOS",
    "contact.partnership": "Бизнес-партнёрство",
    "contact.partnership_desc": "Возможности партнёрства",
    "contact.support": "Поддержка клиентов",
    "contact.support_desc": "Помощь с продуктами",
    "contact.careers_cat": "Карьера",
    "contact.careers_desc": "Возможности трудоустройства",
    "contact.investor_cat": "Отношения с инвесторами",
    "contact.investor_desc": "Инвестиционные запросы",
    "contact.send_message": "Отправить сообщение",
    "contact.first_name": "Имя",
    "contact.last_name": "Фамилия",
    "contact.email": "Email адрес",
    "contact.phone": "Номер телефона",
    "contact.subject": "Тема",
    "contact.select_topic": "Выберите тему",
    "contact.message": "Сообщение",
    "contact.message_placeholder": "Чем мы можем помочь?",
    "contact.sending": "Отправка...",
    "contact.send": "Отправить",
    "contact.info_title": "Контактная информация",
    "contact.email_label": "Email",
    "contact.phone_label": "Телефон",
    "contact.headquarters": "Штаб-квартира",
    "contact.business_hours": "Рабочие часы",
    "contact.hours_value": "Понедельник - Пятница: 9:00 - 18:00 (время Узбекистана)",
    "contact.follow_us": "Подписывайтесь",
    "contact.faq_title": "Часто задаваемые вопросы",
    "contact.toast_title": "Сообщение отправлено!",
    "contact.toast_desc": "Спасибо за обращение. Мы ответим в течение 24-48 часов.",
    "contact.subject_general": "Общий запрос",
    "contact.subject_partnership": "Бизнес-партнёрство",
    "contact.subject_support": "Поддержка клиентов",
    "contact.subject_careers": "Карьера",
    "contact.subject_investors": "Отношения с инвесторами",
    "contact.subject_media": "СМИ и пресса",
    "contact.subject_other": "Другое",

    // Investors Page
    "investors.badge": "Отношения с инвесторами",
    "investors.title_1": "Инвестируйте в ",
    "investors.title_2": "будущее",
    "investors.subtitle": "Присоединяйтесь к строительству будущего инноваций. ALSAMOS предлагает уникальные инвестиционные возможности в 100+ отраслях.",
    "investors.become_investor": "Стать инвестором",
    "investors.download_deck": "Скачать презентацию",
    "investors.performance": "Показатели",
    "investors.key_metrics": "Ключевые метрики",
    "investors.at_a_glance": "Наши показатели одним взглядом",
    "investors.growth_title": "Траектория роста",
    "investors.growth_subtitle": "Стабильный рост по всем показателям",
    "investors.revenue_growth": "Рост выручки ($M)",
    "investors.revenue_by_sector": "Выручка по секторам",
    "investors.opportunities_title": "Инвестиционные возможности",
    "investors.opportunities_subtitle": "Текущие возможности инвестирования в ALSAMOS",
    "investors.min_investment": "Мин. инвестиция",
    "investors.status": "Статус",
    "investors.deadline": "Срок",
    "investors.learn_more": "Подробнее",
    "investors.documents_title": "Документы для инвесторов",
    "investors.documents_subtitle": "Скачайте наши последние отчёты и презентации",
    "investors.download": "Скачать",
    "investors.contact_title": "Свяжитесь с нами",
    "investors.contact_subtitle": "Заинтересованы в инвестировании? Заполните форму, и наша команда свяжется с вами.",
    "investors.toast_title": "Спасибо за ваш интерес!",
    "investors.toast_desc": "Наша команда по работе с инвесторами свяжется с вами в течение 2 рабочих дней.",

    // Contact - FAQ
    "contact.faq_subtitle": "Быстрые ответы на частые вопросы",
    "contact.map_title": "Наше глобальное присутствие",
    "contact.map_subtitle": "Офисы в крупных городах мира",

    // Investors - Form
    "investors.request_info": "Запросить информацию",
    "investors.first_name": "Имя",
    "investors.last_name": "Фамилия",
    "investors.email_label": "Email адрес",
    "investors.company": "Компания/Организация",
    "investors.investment_range": "Диапазон инвестиций",
    "investors.investment_placeholder": "напр., $500K - $1M",
    "investors.message": "Сообщение",
    "investors.message_placeholder": "Расскажите о ваших инвестиционных интересах...",
    "investors.submitting": "Отправка...",
    "investors.submit": "Отправить запрос",
    "investors.contact_desc": "Заинтересованы в инвестировании в ALSAMOS? Наша команда по работе с инвесторами готова ответить на ваши вопросы.",

    // Careers - extra
    "careers.cta_button": "Связаться",

    // 404
    "notfound.title": "404",
    "notfound.message": "Упс! Страница не найдена",
    "notfound.back": "Вернуться на главную",

    // Common
    "common.learn_more": "Подробнее",
    "common.visit_site": "Перейти на сайт",
    "common.read_more": "Читать далее",
    "common.view_all": "Посмотреть все",
    "common.search": "Поиск...",
  },
};

export const LanguageProvider = ({ children }: { children: ReactNode }) => {
  const [language, setLanguageState] = useState<Language>("en");

  useEffect(() => {
    const savedLang = localStorage.getItem("language") as Language;
    if (savedLang && ["en", "uz", "ru"].includes(savedLang)) {
      setLanguageState(savedLang);
    }
  }, []);

  const setLanguage = (lang: Language) => {
    setLanguageState(lang);
    localStorage.setItem("language", lang);
  };

  const t = (key: string): string => {
    return translations[language][key] || translations["en"][key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error("useLanguage must be used within LanguageProvider");
  }
  return context;
};
