import { useState, useEffect, useCallback, useRef } from 'react';
import { supabase } from '@/integrations/supabase/client';
import { useAuth } from '@/contexts/AuthContext';
import { useToast } from '@/hooks/use-toast';

const PAGE_SIZE = 24;
const NEAR_BOTTOM = 900;

export interface Category { id:string; name:string; slug:string; icon:string|null; position:number; }
export interface Seller { id:string; user_id:string; business_name:string; business_type:string; description:string|null; logo_url:string|null; location:string|null; is_verified:boolean; rating:number; total_sales:number; status:string; profile?:{username:string|null;display_name:string|null;avatar_url:string|null}; }
export interface Product { id:string;seller_id:string;category_id:string|null;title:string;description:string|null;price:number;compare_at_price:number|null;currency:string;quantity:number;condition:string;location:string|null;shipping_available:boolean;shipping_price:number;is_negotiable:boolean;is_featured:boolean;status:string;views_count:number;likes_count:number;created_at:string;images:{id:string;url:string;position:number}[];seller?:Seller;category?:Category;is_liked?:boolean; }
export interface CartItem { id:string;product_id:string;quantity:number;product?:Product; }

export function useCategories(){const[categories,setCategories]=useState<Category[]>([]);const[isLoading,setIsLoading]=useState(true);useEffect(()=>{let mounted=true;void supabase.from('product_categories').select('*').order('position').then(({data})=>{if(!mounted)return;if(data)setCategories(data);setIsLoading(false);});return()=>{mounted=false;};},[]);return{categories,isLoading};}

function useNearBottom(loadMore:()=>Promise<void>|void){useEffect(()=>{let ticking=false;const onScroll=()=>{if(ticking)return;ticking=true;requestAnimationFrame(()=>{ticking=false;if(innerHeight+scrollY>=document.documentElement.scrollHeight-NEAR_BOTTOM)void loadMore();});};addEventListener('scroll',onScroll,{passive:true});return()=>removeEventListener('scroll',onScroll);},[loadMore]);}

export function useProducts(categorySlug?:string,searchQuery?:string){
 const{user}=useAuth();const{toast}=useToast();const[products,setProducts]=useState<Product[]>([]);const[isLoading,setIsLoading]=useState(true);const[isLoadingMore,setIsLoadingMore]=useState(false);const[hasMore,setHasMore]=useState(true);const[offset,setOffset]=useState(0);const requestId=useRef(0);const loadingRef=useRef(false);
 const fetchPage=useCallback(async(start:number,append:boolean)=>{if(loadingRef.current)return;loadingRef.current=true;const request=++requestId.current;append?setIsLoadingMore(true):setIsLoading(true);try{let q=supabase.from('products').select('*,seller:sellers(id,user_id,business_name,business_type,logo_url,location,is_verified,rating,total_sales,profile:profiles(username,display_name,avatar_url)),category:product_categories(id,name,slug,icon),images:product_images(id,url,position)').eq('status','active').order('created_at',{ascending:false});if(categorySlug&&categorySlug!=='all'){const{data:cat,error:catError}=await supabase.from('product_categories').select('id').eq('slug',categorySlug).maybeSingle();if(catError)throw catError;if(!cat){if(request===requestId.current){setProducts([]);setHasMore(false);setOffset(0);}return;}q=q.eq('category_id',cat.id);}if(searchQuery?.trim())q=q.ilike('title',`%${searchQuery.trim()}%`);const{data,error}=await q.range(start,start+PAGE_SIZE-1);if(error)throw error;if(request!==requestId.current)return;let liked:string[]=[];if(user){const{data:likes,error:likeError}=await supabase.from('product_likes').select('product_id').eq('user_id',user.id);if(likeError)throw likeError;liked=likes?.map(x=>x.product_id)||[];}if(request!==requestId.current)return;const page=data?.map(p=>({...p,seller:p.seller as unknown as Seller,category:p.category as unknown as Category,images:(p.images as Product['images']).sort((a,b)=>a.position-b.position),is_liked:liked.includes(p.id)})) as Product[]||[];setProducts(prev=>append?[...prev,...page]:page);setHasMore(page.length===PAGE_SIZE);setOffset(start+page.length);}catch(error){if(request===requestId.current)toast({title:'Marketplace error',description:error instanceof Error?error.message:'Failed to load products',variant:'destructive'});}finally{if(request===requestId.current){setIsLoading(false);setIsLoadingMore(false);}loadingRef.current=false;}},[categorySlug,searchQuery,user,toast]);
 const refresh=useCallback(()=>{requestId.current++;setOffset(0);setHasMore(true);return fetchPage(0,false);},[fetchPage]);const loadMore=useCallback(()=>hasMore&&!isLoading&&!isLoadingMore?fetchPage(offset,true):Promise.resolve(),[fetchPage,hasMore,isLoading,isLoadingMore,offset]);useEffect(()=>{void refresh();},[refresh]);useNearBottom(loadMore);return{products,isLoading,isLoadingMore,hasMore,refresh,loadMore};
}

export function useSellerProducts(){const{user}=useAuth();const{toast}=useToast();const[products,setProducts]=useState<Product[]>([]);const[seller,setSeller]=useState<Seller|null>(null);const[isLoading,setIsLoading]=useState(true);const[isLoadingMore,setIsLoadingMore]=useState(false);const[hasMore,setHasMore]=useState(true);const[offset,setOffset]=useState(0);const loadingRef=useRef(false);
 const fetchPage=useCallback(async(start:number,append:boolean)=>{if(loadingRef.current)return;loadingRef.current=true;append?setIsLoadingMore(true):setIsLoading(true);try{if(!user){setProducts([]);setSeller(null);setHasMore(false);return;}const{data:s,error:sellerError}=await supabase.from('sellers').select('*').eq('user_id',user.id).maybeSingle();if(sellerError)throw sellerError;if(!s){setProducts([]);setSeller(null);setHasMore(false);setOffset(0);return;}setSeller(s as Seller);const{data,error}=await supabase.from('products').select('*,category:product_categories(id,name,slug,icon),images:product_images(id,url,position)').eq('seller_id',s.id).neq('status','deleted').order('created_at',{ascending:false}).range(start,start+PAGE_SIZE-1);if(error)throw error;const page=data?.map(p=>({...p,category:p.category as unknown as Category,images:(p.images as Product['images']).sort((a,b)=>a.position-b.position)})) as Product[]||[];setProducts(prev=>append?[...prev,...page]:page);setHasMore(page.length===PAGE_SIZE);setOffset(start+page.length);}catch(error){toast({title:'Seller products error',description:error instanceof Error?error.message:'Failed to load seller products',variant:'destructive'});}finally{setIsLoading(false);setIsLoadingMore(false);loadingRef.current=false;}},[user,toast]);
 const refresh=useCallback(()=>{setOffset(0);setHasMore(true);return fetchPage(0,false);},[fetchPage]);const loadMore=useCallback(()=>hasMore&&!isLoading&&!isLoadingMore?fetchPage(offset,true):Promise.resolve(),[fetchPage,hasMore,isLoading,isLoadingMore,offset]);useEffect(()=>{void refresh();},[refresh]);useNearBottom(loadMore);return{products,seller,isLoading,isLoadingMore,hasMore,refresh,loadMore};}

export function useSavedProducts(){const{user}=useAuth();const{toast}=useToast();const[products,setProducts]=useState<Product[]>([]);const[isLoading,setIsLoading]=useState(true);const[isLoadingMore,setIsLoadingMore]=useState(false);const[hasMore,setHasMore]=useState(true);const[offset,setOffset]=useState(0);const loadingRef=useRef(false);
 const fetchPage=useCallback(async(start:number,append:boolean)=>{if(loadingRef.current)return;loadingRef.current=true;append?setIsLoadingMore(true):setIsLoading(true);try{if(!user){setProducts([]);setHasMore(false);return;}const{data,error}=await supabase.from('product_likes').select('product:products(*,seller:sellers(id,business_name,logo_url,is_verified,rating,location),category:product_categories(id,name,slug,icon),images:product_images(id,url,position))').eq('user_id',user.id).order('created_at',{ascending:false}).range(start,start+PAGE_SIZE-1);if(error)throw error;const page=data?.map(x=>x.product).filter(Boolean).map(p=>({...p as unknown as Product,is_liked:true,images:((p as unknown as Product).images||[]).sort((a,b)=>a.position-b.position)}))||[];setProducts(prev=>append?[...prev,...page]:page);setHasMore(page.length===PAGE_SIZE);setOffset(start+page.length);}catch(error){toast({title:'Saved products error',description:error instanceof Error?error.message:'Failed to load saved products',variant:'destructive'});}finally{setIsLoading(false);setIsLoadingMore(false);loadingRef.current=false;}},[user,toast]);
 const refresh=useCallback(()=>{setOffset(0);setHasMore(true);return fetchPage(0,false);},[fetchPage]);const loadMore=useCallback(()=>hasMore&&!isLoading&&!isLoadingMore?fetchPage(offset,true):Promise.resolve(),[fetchPage,hasMore,isLoading,isLoadingMore,offset]);useEffect(()=>{void refresh();},[refresh]);useNearBottom(loadMore);return{products,isLoading,isLoadingMore,hasMore,refresh,loadMore};}

export function useCart(){const{user}=useAuth();const{toast}=useToast();const[items,setItems]=useState<CartItem[]>([]);const[isLoading,setIsLoading]=useState(true);const fetchCart=useCallback(async()=>{if(!user){setItems([]);setIsLoading(false);return;}const{data,error}=await supabase.from('cart_items').select('*,product:products(*,seller:sellers(id,business_name,is_verified),images:product_images(id,url,position))').eq('user_id',user.id);if(!error&&data)setItems(data.map(i=>({...i,product:i.product as unknown as Product})));setIsLoading(false);},[user]);useEffect(()=>{void fetchCart();},[fetchCart]);const addToCart=async(productId:string,quantity=1)=>{if(!user){toast({title:'Please login',description:'You need to login to add items to cart',variant:'destructive'});return false;}const{error}=await supabase.from('cart_items').upsert({user_id:user.id,product_id:productId,quantity},{onConflict:'user_id,product_id'});if(error){toast({title:'Error',description:'Failed to add to cart',variant:'destructive'});return false;}toast({title:'Added to cart',description:'Product added to your cart'});void fetchCart();return true;};const removeFromCart=async(id:string)=>{const{error}=await supabase.from('cart_items').delete().eq('id',id);if(!error){setItems(x=>x.filter(i=>i.id!==id));toast({title:'Removed',description:'Item removed from cart'});}};const updateQuantity=async(id:string,quantity:number)=>{if(quantity<1)return removeFromCart(id);const{error}=await supabase.from('cart_items').update({quantity}).eq('id',id);if(!error)setItems(x=>x.map(i=>i.id===id?{...i,quantity}:i));};const clearCart=async()=>{if(!user)return;await supabase.from('cart_items').delete().eq('user_id',user.id);setItems([]);};const total=items.reduce((s,i)=>s+(i.product?.price||0)*i.quantity,0);return{items,isLoading,total,addToCart,removeFromCart,updateQuantity,clearCart,refresh:fetchCart};}

export function useProductActions(){const{user}=useAuth();const{toast}=useToast();const toggleLike=async(productId:string,isLiked:boolean)=>{if(!user){toast({title:'Please login',description:'You need to login to save items',variant:'destructive'});return false;}const{error}=isLiked?await supabase.from('product_likes').delete().eq('product_id',productId).eq('user_id',user.id):await supabase.from('product_likes').insert({product_id:productId,user_id:user.id});if(error){toast({title:'Error',description:error.message,variant:'destructive'});return false;}return true;};const createSeller=async(businessName:string,businessType:string,description?:string)=>{if(!user)return null;const{data,error}=await supabase.from('sellers').insert({user_id:user.id,business_name:businessName,business_type:businessType,description}).select().single();if(error){toast({title:'Error',description:error.message,variant:'destructive'});return null;}toast({title:'Success',description:'Your seller account is ready!'});return data;};const createProduct=async(product:{title:string;description?:string;price:number;category_id?:string;condition?:string;location?:string;quantity?:number;is_negotiable?:boolean;shipping_available?:boolean;shipping_price?:number},imageUrls:string[])=>{if(!user)return null;const{data:seller}=await supabase.from('sellers').select('id').eq('user_id',user.id).single();if(!seller){toast({title:'Error',description:'Please create a seller account first',variant:'destructive'});return null;}const{data,error}=await supabase.from('products').insert({seller_id:seller.id,...product}).select().single();if(error){toast({title:'Error',description:error.message,variant:'destructive'});return null;}if(imageUrls.length)await supabase.from('product_images').insert(imageUrls.map((url,i)=>({product_id:data.id,url,position:i})));toast({title:'Success',description:'Product listed successfully!'});return data;};const updateProduct=async(productId:string,updates:Partial<Product>)=>{const{error}=await supabase.from('products').update(updates).eq('id',productId);if(error){toast({title:'Error',description:error.message,variant:'destructive'});return false;}return true;};const deleteProduct=async(productId:string)=>{const{error}=await supabase.from('products').update({status:'deleted'}).eq('id',productId);if(error){toast({title:'Error',description:error.message,variant:'destructive'});return false;}return true;};return{toggleLike,createSeller,createProduct,updateProduct,deleteProduct};}
