apiVersion: v1
kind: ConfigMap
metadata:
  name: coredns-custom
  namespace: kube-system
data:
  alsamos.server: |
    alsamos.com:53 {
        errors
        cache 30
        forward . 1.1.1.1 1.0.0.1
    }
