import { useState, useRef, useEffect } from 'react';
import { motion, AnimatePresence } from 'framer-motion';
import { X, Send, Bot, User, Image as ImageIcon, Trash2, Sparkles, AlertTriangle, Paperclip, Loader2, FileText, Film } from 'lucide-react';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { ScrollArea } from '@/components/ui/scroll-area';
import { Avatar, AvatarFallback, AvatarImage } from '@/components/ui/avatar';
import { useAI } from '@/contexts/AIContext';
import { useAuth } from '@/contexts/AuthContext';
import { useFileUpload } from '@/hooks/useFileUpload';
import { cn } from '@/lib/utils';
import { toast } from 'sonner';

export function AIChatDialog() {
  const { profile } = useAuth();
  const { messages, isLoading, isOpen, setIsOpen, sendMessage, generateImage, clearMessages, checkTimeLimit } = useAI();
  const [input, setInput] = useState(''); const [imagePrompt, setImagePrompt] = useState(''); const [showImageGen, setShowImageGen] = useState(false); const [generatedImage, setGeneratedImage] = useState<string | null>(null); const [timeLimitWarning, setTimeLimitWarning] = useState<string | null>(null); const [attachments, setAttachments] = useState<Array<{ url: string; name: string; type: string }>>([]);
  const { uploadFile, uploading, getFileType } = useFileUpload();
  const messagesEndRef = useRef<HTMLDivElement>(null); const inputRef = useRef<HTMLInputElement>(null); const fileInputRef = useRef<HTMLInputElement>(null);
  useEffect(() => { if (!isOpen) return; inputRef.current?.focus(); checkTimeLimit().then(({ exceeded, usedMinutes, limitMinutes }) => { if (exceeded && limitMinutes) setTimeLimitWarning(`Kunlik ${limitMinutes} daqiqa limitga yetdingiz (${usedMinutes} daqiqa foydalandingiz)`); }); }, [isOpen, checkTimeLimit]);
  useEffect(() => { messagesEndRef.current?.scrollIntoView({ behavior: 'smooth' }); }, [messages]);
  const handleSend = async () => { if ((!input.trim() && attachments.length === 0) || isLoading) return; let message = input.trim(); if (attachments.length) { const text = attachments.map(a => `[${a.type}] ${a.name}: ${a.url}`).join('\n'); message = message ? `${message}\n\n${text}` : text; } setInput(''); setAttachments([]); await sendMessage(message); };
  const handleFilePick = async (e: React.ChangeEvent<HTMLInputElement>) => { const files = Array.from(e.target.files || []); e.target.value = ''; for (const file of files) { if (file.size > 20 * 1024 * 1024) { toast.error(`${file.name}: 20MB dan katta`); continue; } const res = await uploadFile(file); if (res) setAttachments(prev => [...prev, { url: res.url, name: res.name, type: getFileType(res.type) }]); else toast.error(`${file.name} yuklanmadi`); } };
  const handleGenerateImage = async () => { if (!imagePrompt.trim()) return; const url = await generateImage(imagePrompt); if (url) { setGeneratedImage(url); toast.success('Rasm muvaffaqiyatli yaratildi!'); } else toast.error('Rasm yaratishda xatolik'); };
  const quickActions = [{ label: "To'lovlarim haqida", prompt: "Mening so'nggi to'lovlarim haqida ma'lumot ber" }, { label: 'Statistikam', prompt: 'Mening platformadagi statistikalarimni ko\'rsat' }, { label: 'Trend mavzular', prompt: 'Hozirgi trend mavzular qanday?' }];
  if (!isOpen) return null;
  return <AnimatePresence><motion.div initial={{ opacity: 0, y: 24 }} animate={{ opacity: 1, y: 0 }} exit={{ opacity: 0, y: 24 }} className={cn('fixed z-50 flex flex-col overflow-hidden bg-background border border-border shadow-2xl', 'inset-0 rounded-none', 'sm:inset-auto sm:bottom-6 sm:right-6 sm:w-[min(440px,calc(100vw-2rem))] sm:h-[min(720px,calc(100dvh-3rem))] sm:rounded-2xl')}>
    <header className="flex shrink-0 items-center justify-between border-b border-border bg-gradient-to-r from-primary/10 to-primary/5 px-3 py-3 sm:p-4"><div className="flex min-w-0 items-center gap-3"><div className="flex h-9 w-9 shrink-0 items-center justify-center rounded-full bg-gradient-to-br from-primary to-primary/60"><Bot className="h-4 w-4 text-primary-foreground" /></div><div className="min-w-0"><h3 className="font-semibold truncate">Alsamos AI</h3><p className="text-[11px] text-muted-foreground truncate">Sizga yordam berishga tayyorman</p></div></div><div className="flex gap-1"><Button variant="ghost" size="icon" onClick={clearMessages} className="h-8 w-8"><Trash2 className="h-4 w-4" /></Button><Button variant="ghost" size="icon" onClick={() => setIsOpen(false)} className="h-8 w-8"><X className="h-4 w-4" /></Button></div></header>
    {timeLimitWarning && <div className="shrink-0 border-b border-yellow-500/20 bg-yellow-500/10 px-3 py-2"><p className="text-xs text-yellow-600 dark:text-yellow-400 flex items-center gap-2"><AlertTriangle className="h-3 w-3" />{timeLimitWarning}</p></div>}
    <ScrollArea className="min-h-0 flex-1 p-3 sm:p-4">{messages.length === 0 ? <div className="flex min-h-full flex-col items-center justify-center gap-4 py-8"><div className="flex h-14 w-14 items-center justify-center rounded-full bg-primary/10"><Sparkles className="h-7 w-7 text-primary" /></div><p className="text-center text-sm text-muted-foreground">Salom! Men Alsamos AI yordamchisiman.<br />Sizga qanday yordam bera olaman?</p><div className="flex flex-wrap justify-center gap-2">{quickActions.map(a => <Button key={a.label} variant="outline" size="sm" className="max-w-full text-xs" onClick={() => sendMessage(a.prompt)}>{a.label}</Button>)}</div></div> : <div className="space-y-4">{messages.map((msg, i) => <div key={i} className={cn('flex gap-2.5', msg.role === 'user' ? 'justify-end' : 'justify-start')}>{msg.role === 'assistant' && <div className="h-8 w-8 shrink-0 rounded-full bg-gradient-to-br from-primary to-primary/60 flex items-center justify-center"><Bot className="h-4 w-4 text-primary-foreground" /></div>}<div className={cn('max-w-[82%] rounded-2xl px-3.5 py-2 text-sm break-words', msg.role === 'user' ? 'bg-primary text-primary-foreground rounded-tr-none' : 'bg-muted text-foreground rounded-tl-none')}><p className="whitespace-pre-wrap">{msg.content}</p>{msg.imageUrl && <img src={msg.imageUrl} alt="Generated" className="mt-2 max-h-80 max-w-full rounded-lg object-contain" />}</div>{msg.role === 'user' && <Avatar className="h-8 w-8 shrink-0"><AvatarImage src={profile?.avatar_url || ''} /><AvatarFallback><User className="h-4 w-4" /></AvatarFallback></Avatar>}</div>)}{isLoading && <div className="flex gap-2.5"><div className="h-8 w-8 rounded-full bg-gradient-to-br from-primary to-primary/60 flex items-center justify-center"><Bot className="h-4 w-4 text-primary-foreground" /></div><div className="bg-muted rounded-2xl px-4 py-2"><div className="flex gap-1"><span className="h-2 w-2 bg-muted-foreground/50 rounded-full animate-bounce" /><span className="h-2 w-2 bg-muted-foreground/50 rounded-full animate-bounce [animation-delay:150ms]" /><span className="h-2 w-2 bg-muted-foreground/50 rounded-full animate-bounce [animation-delay:300ms]" /></div></div></div>}<div ref={messagesEndRef} /></div>}</ScrollArea>
    {showImageGen && <div className="shrink-0 border-t border-border bg-muted/50 p-3"><div className="flex gap-2"><Input value={imagePrompt} onChange={e => setImagePrompt(e.target.value)} placeholder="Rasm tavsifini kiriting..." className="min-w-0 flex-1" /><Button onClick={handleGenerateImage} disabled={isLoading || !imagePrompt.trim()}><Sparkles className="h-4 w-4" /></Button></div>{generatedImage && <img src={generatedImage} alt="Generated" className="mt-2 max-h-40 max-w-full rounded-lg object-contain" />}</div>}
    <div className="shrink-0 border-t border-border bg-background p-2.5 pb-[max(0.625rem,env(safe-area-inset-bottom))] sm:p-4"><input ref={fileInputRef} type="file" multiple className="hidden" onChange={handleFilePick} />{attachments.length > 0 && <div className="mb-2 flex max-h-20 flex-wrap gap-1.5 overflow-y-auto">{attachments.map((a, i) => <div key={i} className="flex max-w-[calc(100%-0.25rem)] items-center gap-1.5 rounded-lg bg-muted/60 py-1 pl-2 pr-1 text-xs"><span className="truncate">{a.name}</span><button onClick={() => setAttachments(prev => prev.filter((_, idx) => idx !== i))} className="shrink-0 rounded p-0.5 hover:bg-background"><X className="h-3 w-3" /></button></div>)}</div>}<div className="flex items-end gap-1.5 rounded-2xl border border-border/70 bg-muted/30 p-1.5"><Button variant="ghost" size="icon" onClick={() => fileInputRef.current?.click()} disabled={uploading} className="h-9 w-9 shrink-0">{uploading ? <Loader2 className="h-4 w-4 animate-spin" /> : <Paperclip className="h-4 w-4" />}</Button><Button variant={showImageGen ? 'secondary' : 'ghost'} size="icon" onClick={() => setShowImageGen(v => !v)} className="h-9 w-9 shrink-0"><ImageIcon className="h-4 w-4" /></Button><Input ref={inputRef} value={input} onChange={e => setInput(e.target.value)} onKeyDown={e => e.key === 'Enter' && !e.shiftKey && handleSend()} placeholder="Xabar yozing..." disabled={isLoading} className="h-9 min-w-0 flex-1 border-0 bg-transparent px-1 shadow-none focus-visible:ring-0" /><Button onClick={handleSend} disabled={isLoading || (!input.trim() && !attachments.length)} size="icon" className="h-9 w-9 shrink-0 rounded-xl"><Send className="h-4 w-4" /></Button></div><p className="mt-1 hidden px-2 text-[9px] text-muted-foreground sm:block">Enter — yuborish · Shift+Enter — yangi qator</p></div>
  </motion.div></AnimatePresence>;
}
